spec:
  template:
    spec:
      containers:
        - name: springbootdemo
          imagePullPolicy: Always
          env:
            - name: TZ
              value: 'Asia/Shanghai'
            - name: JAVA_OPTIONS
              value: '-Dspring.profiles.active=dev'
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: promethus
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
